version: '3.4'

services:
  samba:
    image: igluko/samba
    environment:
      TZ: 'Europe/Moscow'
    networks:
      - default
    ports:
      - "139:139"
      - "445:445"
    restart: unless-stopped
    volumes:
      - /home/pirate/docker/makefile:/share/folder
      #- /path/to/be/shared:/share/folder
    command: '-u "1000:1000:pirate:pirate:put-any-password-here" -s "SmbShare:/share/folder:rw:pirate"'
    # command: '-u "uid:guid:username:groupname:put-any-password-here" -s "SmbShare:/share/folder:rw:username"'

# networks:
  # default:
